create table country
(
    id   bigint generated by default as identity primary key,
    name varchar(255)
);

create table person
(
    id         bigint generated by default as identity primary key,
    name       varchar(255),
    country_id bigint
        constraint fk__person_country references country
);